name: GitHub Auto Render CD Deployment

on:
  push:
    branches:
      - main  

jobs:
  Deploy-on-Render:
    runs-on: ubuntu-latest

    steps:
  
      - name: Instalar Render CLI
        run: |
           curl -fsSL https://raw.githubusercontent.com/render-oss/cli/refs/heads/main/bin/install.sh | sh
          
      - name: Trigger deploy with Render CLI
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          CI: true
        run: |
          render login ${{ secrets.RENDER_API_KEY }}
          render deploys create ${{ secrets.RENDER_SERVICE_ID }} --output json --confirm  --wait -o
