name: GitHub Auto Render CD Deployment

on:
  push:
    branches:
      - main

jobs:
  Deploy-on-Render:
    runs-on: ubuntu-latest
    steps:
   
      - name: Install Render CLI
        run: curl -fsSL https://render.com/download/render-cli.sh | bash

      - name: Trigger deploy with Render CLI
        run: |
          render deploys create ${{ secrets.RENDER_SERVICE_ID }} --api-key ${{ secrets.RENDER_API_KEY }} --wait --confirm
